# Generated by Django 6.0.2 on 2026-03-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_eventattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societyadmin',
            name='role',
        ),
    ]
