# Generated by Django 6.0.2 on 2026-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_societyadmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='event_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
