# Generated by Django 6.0.2 on 2026-03-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_notificationpreference_event_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocietyAdmin',
        ),
    ]
