# Generated by Django 6.0.2 on 2026-03-26 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_delete_societyadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='authentication.society'),
        ),
    ]
