# Generated by Django 6.0.2 on 2026-03-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_membership_society'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='event_notifications',
            new_name='notify_24hr_reminder',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='notify',
            new_name='notify_cancellations',
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_event_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_new_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
